version: '3.4'

services:
  mf-nginx:
    build:
      context: .
    container_name: mf-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - mf

networks:
  mf:
    external: true